
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tony Nguyen
email: tony.sn@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my profile page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonysn.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: 7onylegit
github:
  username: tony-sn
github: [metadata]
comments:
    provider: "disqus"
    disqus:
      shortname: "tonysn-com"
    # provider: "facebook"
    # facebook:
    #   appid: 263027689048158
    #   num_posts:
    #   colorscheme: "light"

search: true

layout: posts

locale: en-AU

logo: "/assets/images/TonyNguyenLogo.png"
masthead_title: "7ony Nguyen - A Forest Of Knowledge"

head_scripts:
  - /assets/js/scroll-to-top.js
  - /assets/js/progress-bar.js

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://facebook.com/7onysn
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/7onylegit"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/t.o.n.y.1.2.1.1"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tony-sn"

minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
    - _pages


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true
      toc: true
      toc_sticky: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
